/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    submissions: Submission;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    primaryText?: string | null;
    secondaryText?: string | null;
    type:
      | 'none'
      | 'benepleHome'
      | 'highImpact'
      | 'mediumImpact'
      | 'lowImpact'
      | 'tailoredHero'
      | 'benepleWithForm'
      | 'insuranceHero';
    richText?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
    logoCloudHeading?: string | null;
    showLogoCloud?: boolean | null;
    logoCloudLogos?:
      | {
          image: string | Media;
          id?: string | null;
        }[]
      | null;
    formSettings?: {
      portalId: string;
      formId: string;
      region?: string | null;
    };
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | HubSpotFormBlock
    | FeaturesGridBlock
    | TestimonialsBlock
    | LogoCloudBlock
    | InteractiveBallsBlock
    | ShapeFeaturesBlock
    | HRFeatureShowcaseBlock
    | StatsDisplayBlock
    | TestimonialsEnhancedBlock
    | CallToActionEnhancedBlock
    | FeatureGridEnhancedBlock
    | PricingEnhancedBlock
    | InteractiveFeaturesBlock
    | SpacerBlock
    | InsuranceFeaturesBlock
    | LandingPageContentBlock
    | InsurancePartnersTickerBlock
    | InsuranceBenefitsBlock
    | InsuranceSolutionsTabsBlock
    | InsuranceStepsBlock
    | InsuranceCaseStudyBlock
    | InsuranceGoogleReviewsBlock
    | InsuranceContactFormBlock
    | InsuranceFooterBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  /**
   * Optional headline displayed above the media
   */
  headline?: string | null;
  /**
   * Optional description displayed below the headline
   */
  subline?: string | null;
  media: string | Media;
  removeBorder?: boolean | null;
  /**
   * Apply a sophisticated multi-layered shadow to the media element
   */
  enableShadow?: boolean | null;
  /**
   * Add one or more CTA buttons displayed below the media
   */
  ctas?:
    | {
        /**
         * Configure the CTA button link and appearance
         */
        cta: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HubSpotFormBlock".
 */
export interface HubSpotFormBlock {
  portalId: string;
  formId: string;
  region?: string | null;
  customStyling?: {
    /**
     * Add custom CSS classes to the form container
     */
    formClassName?: string | null;
    /**
     * Add custom CSS styles for the form
     */
    customCSS?: string | null;
    /**
     * Text shown while form is loading
     */
    loadingText?: string | null;
  };
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hubspotFormBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesGridBlock".
 */
export interface FeaturesGridBlock {
  heading?: string | null;
  subheading?: string | null;
  features?:
    | {
        icon?: (string | null) | Media;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuresGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  /**
   * Main heading for this section
   */
  headline?: string | null;
  /**
   * Optional description or subtitle displayed below the headline
   */
  subline?: string | null;
  testimonials?:
    | {
        quote: string;
        authorName: string;
        authorRole?: string | null;
        authorAvatar?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock".
 */
export interface LogoCloudBlock {
  /**
   * Main heading for this section
   */
  headline?: string | null;
  /**
   * Optional description or subtitle displayed below the headline
   */
  subline?: string | null;
  direction?: ('left' | 'right') | null;
  logos?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoCloud';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InteractiveBallsBlock".
 */
export interface InteractiveBallsBlock {
  /**
   * Main heading for this section
   */
  headline?: string | null;
  /**
   * Optional description or subtitle displayed below the headline
   */
  subline?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'interactiveBalls';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShapeFeaturesBlock".
 */
export interface ShapeFeaturesBlock {
  /**
   * Optional heading above the feature blocks
   */
  heading?: string | null;
  features: {
    title: string;
    /**
     * Optional subtitle text
     */
    subtitle?: string | null;
    variant?: ('primary' | 'secondary' | 'custom') | null;
    /**
     * CSS gradient value, e.g., "linear-gradient(135deg, #667eea 0%, #764ba2 100%)"
     */
    customGradient?: string | null;
    /**
     * Override the default corner style for this variant
     */
    cornerStyle?: ('auto' | 'standard' | 'asymmetric') | null;
    /**
     * Optional background image for this feature block
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Choose the text color for this feature block
     */
    textColor?: ('white' | 'lightblue' | 'darkblue' | 'custom') | null;
    /**
     * Enter a custom color value (hex, rgb, hsl, etc.). Example: #FF6B35 or rgb(255, 107, 53)
     */
    customTextColor?: string | null;
    /**
     * Controls how much horizontal space this block takes up in the layout
     */
    size?: ('full' | 'half' | 'oneThird' | 'twoThirds' | 'oneQuarter' | 'threeQuarters') | null;
    id?: string | null;
  }[];
  layout?: ('grid' | 'row' | 'column') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'shapeFeatures';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HRFeatureShowcaseBlock".
 */
export interface HRFeatureShowcaseBlock {
  title?: string | null;
  subtitle?: string | null;
  layout?: ('grid' | 'list') | null;
  columns?: ('2' | '3' | '4') | null;
  /**
   * CSS gradient class for highlighted features
   */
  highlightColor?: string | null;
  features?:
    | {
        title: string;
        description: string;
        icon?: ('users' | 'clock' | 'chart' | 'shield' | 'document' | 'calendar') | null;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hrFeatureShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsDisplayBlock".
 */
export interface StatsDisplayBlock {
  title?: string | null;
  subtitle?: string | null;
  layout?: ('grid' | 'horizontal' | 'cards') | null;
  columns?: ('2' | '3' | '4' | '5') | null;
  animated?: boolean | null;
  stats?:
    | {
        label: string;
        isTextValue?: boolean | null;
        /**
         * Numeric value for the statistic
         */
        value?: number | null;
        /**
         * Text value for the statistic (used when "Use text value" is enabled)
         */
        textValue?: string | null;
        prefix?: string | null;
        suffix?: string | null;
        description?: string | null;
        icon?: ('' | 'employees' | 'retention' | 'productivity' | 'satisfaction' | 'growth') | null;
        highlight?: boolean | null;
        /**
         * Percentage change (positive or negative)
         */
        trendValue?: number | null;
        trendPeriod?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsDisplay';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsEnhancedBlock".
 */
export interface TestimonialsEnhancedBlock {
  title?: string | null;
  subtitle?: string | null;
  columns?: ('1' | '2' | '3') | null;
  variant?: ('default' | 'minimal' | 'featured') | null;
  showQuotes?: boolean | null;
  testimonials?:
    | {
        content: string;
        authorName: string;
        authorRole: string;
        authorCompany: string;
        authorAvatar?: (string | null) | Media;
        rating?: ('0' | '1' | '2' | '3' | '4' | '5') | null;
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialsEnhanced';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionEnhancedBlock".
 */
export interface CallToActionEnhancedBlock {
  title: string;
  subtitle?: string | null;
  description?: string | null;
  variant?: ('default' | 'centered' | 'split' | 'minimal') | null;
  background?: ('gradient' | 'solid' | 'transparent' | 'pattern') | null;
  /**
   * Tailwind CSS gradient class (e.g., from-blue-600)
   */
  gradientFrom?: string | null;
  /**
   * Tailwind CSS gradient class (e.g., to-purple-600)
   */
  gradientTo?: string | null;
  textAlign?: ('left' | 'center' | 'right') | null;
  size?: ('sm' | 'md' | 'lg' | 'xl') | null;
  image?: {
    media?: (string | null) | Media;
    position?: ('left' | 'right' | 'background') | null;
  };
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline' | 'secondary' | 'ghost') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaEnhanced';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridEnhancedBlock".
 */
export interface FeatureGridEnhancedBlock {
  title?: string | null;
  subtitle?: string | null;
  layout?: ('uniform' | 'masonry' | 'mixed') | null;
  columns?: ('2' | '3' | '4') | null;
  gap?: ('sm' | 'md' | 'lg') | null;
  variant?: ('default' | 'minimal' | 'modern' | 'bordered' | 'compact') | null;
  showImages?: boolean | null;
  /**
   * Show call-to-action button below the subtitle
   */
  showCTA?: boolean | null;
  /**
   * Text for the call-to-action button
   */
  ctaText?: string | null;
  /**
   * URL for the call-to-action button
   */
  ctaUrl?: string | null;
  /**
   * Choose where to display the call-to-action button
   */
  ctaPosition?: ('header' | 'footer') | null;
  /**
   * Optional featured card that spans full width above other cards
   */
  featuredCard?: {
    title?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    icon?:
      | (
          | ''
          | 'insurance-building'
          | 'insurance-corporate'
          | 'insurance-group'
          | 'insurance-medical'
          | 'insurance-special'
          | 'users'
          | 'clock'
          | 'chart'
          | 'shield'
          | 'document'
          | 'calendar'
          | 'heart'
          | 'building'
          | 'cog'
          | 'truck'
          | 'gem'
          | 'licensed-compliant'
          | 'market-access'
          | 'specialist-advisors'
          | 'wellbeing'
        )
      | null;
    image?: (string | null) | Media;
    linkText?: string | null;
    linkUrl?: string | null;
    badge?: string | null;
    colorVariant?: ('brand' | 'default') | null;
  };
  features?:
    | {
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        icon?:
          | (
              | ''
              | 'insurance-building'
              | 'insurance-corporate'
              | 'insurance-group'
              | 'insurance-medical'
              | 'insurance-special'
              | 'users'
              | 'clock'
              | 'chart'
              | 'shield'
              | 'document'
              | 'calendar'
              | 'heart'
              | 'building'
              | 'cog'
              | 'truck'
              | 'gem'
              | 'licensed-compliant'
              | 'market-access'
              | 'specialist-advisors'
              | 'wellbeing'
            )
          | null;
        image?: (string | null) | Media;
        linkText?: string | null;
        linkUrl?: string | null;
        badge?: string | null;
        size?: ('small' | 'medium' | 'large' | 'wide' | 'tall') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGridEnhanced';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingEnhancedBlock".
 */
export interface PricingEnhancedBlock {
  title?: string | null;
  subtitle?: string | null;
  currency?: string | null;
  variant?: ('cards' | 'table' | 'minimal' | 'featured-split') | null;
  showFeatureComparison?: boolean | null;
  showCurrencyToggle?: boolean | null;
  /**
   * Text to display for Dirham currency (e.g., AED)
   */
  dirhamCurrency?: string | null;
  billingToggle?: {
    enabled?: boolean | null;
    monthlyLabel?: string | null;
    yearlyLabel?: string | null;
    discount?: string | null;
  };
  plans?:
    | {
        name: string;
        description?: string | null;
        price?: {
          /**
           * Leave empty for custom pricing like "Contact Us"
           */
          amount?: number | null;
          /**
           * Use for "Contact Us", "Custom", etc.
           */
          customAmount?: string | null;
          /**
           * Optional: Set yearly pricing. Only shown when billing toggle is enabled.
           */
          yearlyAmount?: number | null;
          /**
           * Optional: Custom text for yearly pricing (e.g., "Contact Us")
           */
          yearlyCustomAmount?: string | null;
          /**
           * Show crossed-out original price and calculate discount percentage
           */
          originalAmount?: number | null;
          /**
           * Text to display after the price (e.g., "per user / month", "per seat / year", "one-time"). Leave empty to hide this text.
           */
          periodText?: string | null;
        };
        badge?: string | null;
        highlight?: boolean | null;
        popular?: boolean | null;
        disabled?: boolean | null;
        /**
         * Show the Dirham symbol next to the price for this plan
         */
        showDirhamSymbol?: boolean | null;
        buttonText: string;
        buttonUrl?: string | null;
        buttonVariant?: ('primary' | 'secondary' | 'outline') | null;
        features?:
          | {
              name: string;
              included: 'true' | 'false' | 'partial' | 'custom';
              customText?: string | null;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricingEnhanced';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InteractiveFeaturesBlock".
 */
export interface InteractiveFeaturesBlock {
  /**
   * Main heading for the features section
   */
  heading?: string | null;
  /**
   * Subtitle or description for the features section
   */
  subheading?: string | null;
  features?:
    | {
        /**
         * Feature title that will be clickable
         */
        title: string;
        /**
         * Brief description of the feature
         */
        description: string;
        /**
         * Image that will be displayed when this feature is selected
         */
        image: string | Media;
        /**
         * Optional badge text (e.g., "New", "Popular")
         */
        badge?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Show call-to-action button below the subheading
   */
  showCTA?: boolean | null;
  /**
   * Text for the call-to-action button
   */
  ctaText?: string | null;
  /**
   * URL for the call-to-action button
   */
  ctaUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'interactiveFeatures';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock".
 */
export interface SpacerBlock {
  /**
   * Spacing height for mobile devices (up to 768px)
   */
  mobileHeight: '2' | '3' | '4' | '5' | '6' | '8' | '10' | '12' | '16' | '20' | '24' | '32' | '40' | '48' | '64' | '80';
  /**
   * Spacing height for desktop devices (768px and above)
   */
  desktopHeight:
    | '2'
    | '3'
    | '4'
    | '5'
    | '6'
    | '8'
    | '10'
    | '12'
    | '16'
    | '20'
    | '24'
    | '32'
    | '40'
    | '48'
    | '64'
    | '80'
    | '96'
    | '112'
    | '128';
  /**
   * Optional background color for the spacer area
   */
  backgroundColor?:
    | ('transparent' | 'white' | 'gray-50' | 'gray-100' | 'gray-200' | 'brand-primary' | 'brand-secondary')
    | null;
  /**
   * Show a visual border in admin preview to make spacer visible (not shown on frontend)
   */
  showInAdmin?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'spacer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceFeaturesBlock".
 */
export interface InsuranceFeaturesBlock {
  title?: string | null;
  subtitle?: string | null;
  layout?: ('default' | 'pillars' | 'sticky' | 'tabs' | 'kpi') | null;
  /**
   * Image to display in the left sidebar when using sticky layout
   */
  stickyImage?: (string | null) | Media;
  /**
   * Show the proof strip with license and provider information
   */
  showProofStrip?: boolean | null;
  /**
   * Show call-to-action button below the features
   */
  showCTA?: boolean | null;
  /**
   * Text for the call-to-action button
   */
  ctaText?: string | null;
  /**
   * URL for the call-to-action button
   */
  ctaUrl?: string | null;
  /**
   * Remove padding from the left box (sticky layout only)
   */
  removePaddingLeftBox?: boolean | null;
  features?:
    | {
        icon:
          | 'insurance-building'
          | 'insurance-corporate'
          | 'insurance-group'
          | 'insurance-medical'
          | 'insurance-special'
          | 'arrow'
          | 'licensed-compliant'
          | 'market-access'
          | 'specialist-advisors'
          | 'wellbeing';
        title: string;
        text: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Items to display in the proof strip below features
   */
  proofStrip?:
    | {
        label: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  audienceTabs?: {
    employerLabel?: string | null;
    individualLabel?: string | null;
    commonFeatures?:
      | {
          icon?:
            | (
                | 'insurance-building'
                | 'insurance-corporate'
                | 'insurance-group'
                | 'insurance-medical'
                | 'insurance-special'
              )
            | null;
          title?: string | null;
          subtitle?: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[]
      | null;
    employerFeatures?:
      | {
          icon?:
            | (
                | 'insurance-building'
                | 'insurance-corporate'
                | 'insurance-group'
                | 'insurance-medical'
                | 'insurance-special'
              )
            | null;
          title?: string | null;
          subtitle?: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[]
      | null;
    individualFeatures?:
      | {
          icon?:
            | (
                | 'insurance-building'
                | 'insurance-corporate'
                | 'insurance-group'
                | 'insurance-medical'
                | 'insurance-special'
              )
            | null;
          title?: string | null;
          subtitle?: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[]
      | null;
  };
  kpiBand?: {
    kpis?:
      | {
          key: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'insuranceFeaturesBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LandingPageContentBlock".
 */
export interface LandingPageContentBlock {
  title: string;
  subtitle?: string | null;
  /**
   * Optional additional content below the subtitle
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image: string | Media;
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional text that appears below the features list
   */
  bottomText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  showCTA?: boolean | null;
  ctaText?: string | null;
  ctaUrl?: string | null;
  backgroundColor?: ('white' | 'gray' | 'brand-light') | null;
  imagePosition?: ('right' | 'left') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'landingPageContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsurancePartnersTickerBlock".
 */
export interface InsurancePartnersTickerBlock {
  pillText?: string | null;
  headline?: string | null;
  /**
   * Words to highlight in accent color, separated by commas
   */
  highlightedWords?: string | null;
  row1Logos?:
    | {
        image: string | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  row2Logos?:
    | {
        image: string | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'insurancePartnersTicker';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceBenefitsBlock".
 */
export interface InsuranceBenefitsBlock {
  pillText?: string | null;
  headline?: string | null;
  highlightedWords?: string | null;
  largeNumber?: string | null;
  benefits?:
    | {
        title: string;
        description: string;
        /**
         * Paste SVG markup for the icon
         */
        iconSvg?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'insuranceBenefits';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceSolutionsTabsBlock".
 */
export interface InsuranceSolutionsTabsBlock {
  pillText?: string | null;
  headline?: string | null;
  highlightedWords?: string | null;
  tabs?:
    | {
        tabLabel: string;
        categoryTitle?: string | null;
        categoryDescription?: string | null;
        categoryIconSvg?: string | null;
        solutions?:
          | {
              title: string;
              description?: string | null;
              linkUrl?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'insuranceSolutionsTabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceStepsBlock".
 */
export interface InsuranceStepsBlock {
  pillText?: string | null;
  headline?: string | null;
  highlightedWords?: string | null;
  steps?:
    | {
        stepNumber?: string | null;
        title: string;
        description?: string | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'insuranceSteps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceCaseStudyBlock".
 */
export interface InsuranceCaseStudyBlock {
  pillText?: string | null;
  headline?: string | null;
  highlightedWords?: string | null;
  slides?:
    | {
        industry?: string | null;
        companyLogo?: (string | null) | Media;
        quote?: string | null;
        reviewText?: string | null;
        authorName?: string | null;
        authorRole?: string | null;
        metricText?: string | null;
        metricIconSvg?: string | null;
        chartSvg?: string | null;
        /**
         * Path to logo shown in carousel dots
         */
        navLogoSrc?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'insuranceCaseStudy';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceGoogleReviewsBlock".
 */
export interface InsuranceGoogleReviewsBlock {
  pillText?: string | null;
  headline?: string | null;
  highlightedWords?: string | null;
  googleRating?: string | null;
  reviewCount?: string | null;
  writeReviewUrl?: string | null;
  reviews?:
    | {
        initials: string;
        name: string;
        stars?: number | null;
        date?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'insuranceGoogleReviews';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceContactFormBlock".
 */
export interface InsuranceContactFormBlock {
  pillText?: string | null;
  headline?: string | null;
  subtitle?: string | null;
  hubspotPortalId?: string | null;
  hubspotFormId?: string | null;
  insuranceTypes?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'insuranceContactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceFooterBlock".
 */
export interface InsuranceFooterBlock {
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  categories?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'insuranceFooter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  message?: string | null;
  consent?: boolean | null;
  optInMarketing?: boolean | null;
  companyName?: string | null;
  insuranceRenewalDate?: string | null;
  areaOfInterest?: string | null;
  countryCode?: string | null;
  hubspotSubmitted?: boolean | null;
  hubspotError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: string | Post;
      }
    | {
        relationTo: 'pages';
        value: string | Page;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'submissions';
        value: string | Submission;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: string | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        primaryText?: T;
        secondaryText?: T;
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
        logoCloudHeading?: T;
        showLogoCloud?: T;
        logoCloudLogos?:
          | T
          | {
              image?: T;
              id?: T;
            };
        formSettings?:
          | T
          | {
              portalId?: T;
              formId?: T;
              region?: T;
            };
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        hubspotFormBlock?: T | HubSpotFormBlockSelect<T>;
        featuresGrid?: T | FeaturesGridBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        logoCloud?: T | LogoCloudBlockSelect<T>;
        interactiveBalls?: T | InteractiveBallsBlockSelect<T>;
        shapeFeatures?: T | ShapeFeaturesBlockSelect<T>;
        hrFeatureShowcase?: T | HRFeatureShowcaseBlockSelect<T>;
        statsDisplay?: T | StatsDisplayBlockSelect<T>;
        testimonialsEnhanced?: T | TestimonialsEnhancedBlockSelect<T>;
        ctaEnhanced?: T | CallToActionEnhancedBlockSelect<T>;
        featureGridEnhanced?: T | FeatureGridEnhancedBlockSelect<T>;
        pricingEnhanced?: T | PricingEnhancedBlockSelect<T>;
        interactiveFeatures?: T | InteractiveFeaturesBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
        insuranceFeaturesBlock?: T | InsuranceFeaturesBlockSelect<T>;
        landingPageContent?: T | LandingPageContentBlockSelect<T>;
        insurancePartnersTicker?: T | InsurancePartnersTickerBlockSelect<T>;
        insuranceBenefits?: T | InsuranceBenefitsBlockSelect<T>;
        insuranceSolutionsTabs?: T | InsuranceSolutionsTabsBlockSelect<T>;
        insuranceSteps?: T | InsuranceStepsBlockSelect<T>;
        insuranceCaseStudy?: T | InsuranceCaseStudyBlockSelect<T>;
        insuranceGoogleReviews?: T | InsuranceGoogleReviewsBlockSelect<T>;
        insuranceContactForm?: T | InsuranceContactFormBlockSelect<T>;
        insuranceFooter?: T | InsuranceFooterBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  headline?: T;
  subline?: T;
  media?: T;
  removeBorder?: T;
  enableShadow?: T;
  ctas?:
    | T
    | {
        cta?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HubSpotFormBlock_select".
 */
export interface HubSpotFormBlockSelect<T extends boolean = true> {
  portalId?: T;
  formId?: T;
  region?: T;
  customStyling?:
    | T
    | {
        formClassName?: T;
        customCSS?: T;
        loadingText?: T;
      };
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesGridBlock_select".
 */
export interface FeaturesGridBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  headline?: T;
  subline?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        authorName?: T;
        authorRole?: T;
        authorAvatar?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock_select".
 */
export interface LogoCloudBlockSelect<T extends boolean = true> {
  headline?: T;
  subline?: T;
  direction?: T;
  logos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InteractiveBallsBlock_select".
 */
export interface InteractiveBallsBlockSelect<T extends boolean = true> {
  headline?: T;
  subline?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShapeFeaturesBlock_select".
 */
export interface ShapeFeaturesBlockSelect<T extends boolean = true> {
  heading?: T;
  features?:
    | T
    | {
        title?: T;
        subtitle?: T;
        variant?: T;
        customGradient?: T;
        cornerStyle?: T;
        backgroundImage?: T;
        textColor?: T;
        customTextColor?: T;
        size?: T;
        id?: T;
      };
  layout?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HRFeatureShowcaseBlock_select".
 */
export interface HRFeatureShowcaseBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  layout?: T;
  columns?: T;
  highlightColor?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        highlight?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsDisplayBlock_select".
 */
export interface StatsDisplayBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  layout?: T;
  columns?: T;
  animated?: T;
  stats?:
    | T
    | {
        label?: T;
        isTextValue?: T;
        value?: T;
        textValue?: T;
        prefix?: T;
        suffix?: T;
        description?: T;
        icon?: T;
        highlight?: T;
        trendValue?: T;
        trendPeriod?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsEnhancedBlock_select".
 */
export interface TestimonialsEnhancedBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  columns?: T;
  variant?: T;
  showQuotes?: T;
  testimonials?:
    | T
    | {
        content?: T;
        authorName?: T;
        authorRole?: T;
        authorCompany?: T;
        authorAvatar?: T;
        rating?: T;
        featured?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionEnhancedBlock_select".
 */
export interface CallToActionEnhancedBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  variant?: T;
  background?: T;
  gradientFrom?: T;
  gradientTo?: T;
  textAlign?: T;
  size?: T;
  image?:
    | T
    | {
        media?: T;
        position?: T;
      };
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridEnhancedBlock_select".
 */
export interface FeatureGridEnhancedBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  layout?: T;
  columns?: T;
  gap?: T;
  variant?: T;
  showImages?: T;
  showCTA?: T;
  ctaText?: T;
  ctaUrl?: T;
  ctaPosition?: T;
  featuredCard?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        image?: T;
        linkText?: T;
        linkUrl?: T;
        badge?: T;
        colorVariant?: T;
      };
  features?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        image?: T;
        linkText?: T;
        linkUrl?: T;
        badge?: T;
        size?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingEnhancedBlock_select".
 */
export interface PricingEnhancedBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  currency?: T;
  variant?: T;
  showFeatureComparison?: T;
  showCurrencyToggle?: T;
  dirhamCurrency?: T;
  billingToggle?:
    | T
    | {
        enabled?: T;
        monthlyLabel?: T;
        yearlyLabel?: T;
        discount?: T;
      };
  plans?:
    | T
    | {
        name?: T;
        description?: T;
        price?:
          | T
          | {
              amount?: T;
              customAmount?: T;
              yearlyAmount?: T;
              yearlyCustomAmount?: T;
              originalAmount?: T;
              periodText?: T;
            };
        badge?: T;
        highlight?: T;
        popular?: T;
        disabled?: T;
        showDirhamSymbol?: T;
        buttonText?: T;
        buttonUrl?: T;
        buttonVariant?: T;
        features?:
          | T
          | {
              name?: T;
              included?: T;
              customText?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InteractiveFeaturesBlock_select".
 */
export interface InteractiveFeaturesBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        badge?: T;
        id?: T;
      };
  showCTA?: T;
  ctaText?: T;
  ctaUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock_select".
 */
export interface SpacerBlockSelect<T extends boolean = true> {
  mobileHeight?: T;
  desktopHeight?: T;
  backgroundColor?: T;
  showInAdmin?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceFeaturesBlock_select".
 */
export interface InsuranceFeaturesBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  layout?: T;
  stickyImage?: T;
  showProofStrip?: T;
  showCTA?: T;
  ctaText?: T;
  ctaUrl?: T;
  removePaddingLeftBox?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  proofStrip?:
    | T
    | {
        label?: T;
        description?: T;
        id?: T;
      };
  audienceTabs?:
    | T
    | {
        employerLabel?: T;
        individualLabel?: T;
        commonFeatures?:
          | T
          | {
              icon?: T;
              title?: T;
              subtitle?: T;
              id?: T;
            };
        employerFeatures?:
          | T
          | {
              icon?: T;
              title?: T;
              subtitle?: T;
              id?: T;
            };
        individualFeatures?:
          | T
          | {
              icon?: T;
              title?: T;
              subtitle?: T;
              id?: T;
            };
      };
  kpiBand?:
    | T
    | {
        kpis?:
          | T
          | {
              key?: T;
              label?: T;
              id?: T;
            };
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LandingPageContentBlock_select".
 */
export interface LandingPageContentBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  image?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  bottomText?: T;
  showCTA?: T;
  ctaText?: T;
  ctaUrl?: T;
  backgroundColor?: T;
  imagePosition?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsurancePartnersTickerBlock_select".
 */
export interface InsurancePartnersTickerBlockSelect<T extends boolean = true> {
  pillText?: T;
  headline?: T;
  highlightedWords?: T;
  row1Logos?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  row2Logos?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceBenefitsBlock_select".
 */
export interface InsuranceBenefitsBlockSelect<T extends boolean = true> {
  pillText?: T;
  headline?: T;
  highlightedWords?: T;
  largeNumber?: T;
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        iconSvg?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceSolutionsTabsBlock_select".
 */
export interface InsuranceSolutionsTabsBlockSelect<T extends boolean = true> {
  pillText?: T;
  headline?: T;
  highlightedWords?: T;
  tabs?:
    | T
    | {
        tabLabel?: T;
        categoryTitle?: T;
        categoryDescription?: T;
        categoryIconSvg?: T;
        solutions?:
          | T
          | {
              title?: T;
              description?: T;
              linkUrl?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceStepsBlock_select".
 */
export interface InsuranceStepsBlockSelect<T extends boolean = true> {
  pillText?: T;
  headline?: T;
  highlightedWords?: T;
  steps?:
    | T
    | {
        stepNumber?: T;
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceCaseStudyBlock_select".
 */
export interface InsuranceCaseStudyBlockSelect<T extends boolean = true> {
  pillText?: T;
  headline?: T;
  highlightedWords?: T;
  slides?:
    | T
    | {
        industry?: T;
        companyLogo?: T;
        quote?: T;
        reviewText?: T;
        authorName?: T;
        authorRole?: T;
        metricText?: T;
        metricIconSvg?: T;
        chartSvg?: T;
        navLogoSrc?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceGoogleReviewsBlock_select".
 */
export interface InsuranceGoogleReviewsBlockSelect<T extends boolean = true> {
  pillText?: T;
  headline?: T;
  highlightedWords?: T;
  googleRating?: T;
  reviewCount?: T;
  writeReviewUrl?: T;
  reviews?:
    | T
    | {
        initials?: T;
        name?: T;
        stars?: T;
        date?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceContactFormBlock_select".
 */
export interface InsuranceContactFormBlockSelect<T extends boolean = true> {
  pillText?: T;
  headline?: T;
  subtitle?: T;
  hubspotPortalId?: T;
  hubspotFormId?: T;
  insuranceTypes?:
    | T
    | {
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsuranceFooterBlock_select".
 */
export interface InsuranceFooterBlockSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  address?: T;
  categories?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  message?: T;
  consent?: T;
  optInMarketing?: T;
  companyName?: T;
  insuranceRenewalDate?: T;
  areaOfInterest?: T;
  countryCode?: T;
  hubspotSubmitted?: T;
  hubspotError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  insuranceMegaMenu?: {
    enabled?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
    categories?:
      | {
          title: string;
          description?: string | null;
          icon: 'users' | 'shield' | 'fileText' | 'barChart' | 'building' | 'heart';
          items?:
            | {
                title: string;
                /**
                 * Optional description for internal reference - not displayed in the menu
                 */
                description?: string | null;
                link?: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null);
                  url?: string | null;
                };
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    ctaButtons?: {
      primaryCta?: {
        label?: string | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
        };
      };
      secondaryCta?: {
        label?: string | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
        };
      };
    };
  };
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('link' | 'default' | 'cta' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  columns?:
    | {
        title?: string | null;
        items?:
          | {
              text: string;
              type?: ('text' | 'phone' | 'email' | 'address') | null;
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  socialMedia?: {
    instagram?: string | null;
    linkedin?: string | null;
    facebook?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  insuranceMegaMenu?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        categories?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        ctaButtons?:
          | T
          | {
              primaryCta?:
                | T
                | {
                    label?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                        };
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                        };
                  };
            };
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              text?: T;
              type?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  socialMedia?:
    | T
    | {
        instagram?: T;
        linkedin?: T;
        facebook?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}